apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - name: nocodb-builder
      image: "quay.io/buildah/stable:latest"
      script: |
        yum update -y && \
        yum install -y rsync && \
        curl --silent --location https://rpm.nodesource.com/setup_18.x | bash - && \
        yum -y install nodejs && \
        npm install -g pnpm && \
        pnpm install && \
        pnpm bootstrap && \
        ./build-local-docker-image.sh
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
