apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - image: 'selfhosted.jfrog.io/nocodb-deps/nocodb-install-deps:0.1'
      name: nocodb-builder
      resources: {}
      script: |
        chmod +x build-local-docker-image.sh
        ./build-local-docker-image.sh
      securityContext:
        privileged: true
      workingDir: /app
  workspaces:
    - name: source