apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - name: nocodb-builder
      image: "quay.io/buildah/stable:latest"
      script: |
          buildah login selfhosted.jfrog.io --username=tekton --password=Tekton123@
          buildah --storage-driver=overlay bud --no-cache -f ./tekton/Dockerfiles/Dockerfile.copying-artifacts -t nocodb-runner-image .
          buildah --storage-driver=overlay tag nocodb-runner-image selfhosted.jfrog.io/nocodb-deps/nocodb-runner-image:latest
          buildah --storage-driver=overlay --creds tekton:Tekton123@ push selfhosted.jfrog.io/nocodb-deps/nocodb-runner-image:latest
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
