apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - name: nocodb-builder
      image: "aso-docker-snapshot-local.cfar.nsapps.dcn.aso-nocodb-builder:1.0"
      script: |
          ./build-local-docker-image.sh
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
