apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - name: nocodb-builder
      image: "registry.redhat.io/rhel8/buildah:latest"
      script: |
          ./build-local-docker-image.sh
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
