apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nocodb-builder
  namespace: tekton
spec:
  steps:
    - image: "rafay7655/nocodb-local:latest"
      name: nocodb-builder
      resources: {}
      script: |
        chmod +x build-local-docker-image.sh
        ./build-local-docker-image.sh
      securityContext:
        privileged: true
      workingDir: /app
  workspaces:
    - name: source
