apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-dependencies
  namespace: tekton
spec:
  steps:
    - name: install-dependencies
      image: "quay.io/buildah/stable:latest"
      script: |
          buildah --storage-driver=overlay bud --no-cache -f ./tekton/Dockerfiles/Dockerfile.install-deps -t nocodb-install-deps .
          buildah --storage-driver=overlay tag nocodb-install-deps selfhosted.jfrog.io/nocodb-local/nocodb-install-deps:latest
          buildah --storage-driver=overlay --creds tekton:Tekton123@ push selfhosted.jfrog.io/nocodb-local/nocodb-install-deps:latest
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
