apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: install-dependencies
  namespace: tekton
spec:
  steps:
    - name: install-dependencies
      image: "node:latest"
      script: |
          apt-get update && apt-get install -y buildah
          buildah bud -f /tekton/Dockerfiles/Dockerfile.install-deps -t nocodb-install-deps /tekton/Dockerfiles
          buildah login -umuhammadrafay7655@gmail.com selfhosted.jfrog.io
          buildah tag nocodb-local selfhosted.jfrog.io/nocodb-local/nocodb-local:latest
          buildah push selfhosted.jfrog.io/nocodb-local/nocodb-local:latest
      workingDir: $(workspaces.source.path)/
  workspaces:
    - name: source
