apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
  namespace: tekton-pipelines
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: "https://github.com/MRafaydev/nocodb"
        - name: subdirectory
          value: ""
        - name: revision
          value: main
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: helm-install
      params:
      - name: charts_dir
        value: ./charts/nocodb
      - name: releases_version
        value: v1.0.0
      - name: release_name
        value: helm-nocodb
      runAfter:
        - fetch-repository
      taskRef:
        name: helm-upgrade-from-source
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
