apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-access
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
