###########
# Stage 1: Installing Dependencies & Building GUI
###########
FROM registry.redhat.io/rhel8/buildah:latest 
WORKDIR /app
COPY . .
RUN yum update -y && \
    yum install -y rsync && \
    curl --silent --location https://rpm.nodesource.com/setup_18.x | bash - && \
    yum -y install nodejs && \
    npm install -g pnpm