###########
# Stage 1: Installing Dependencies & Building GUI
###########
FROM node:latest AS build
ENV SCRIPT_DIR /app
WORKDIR ${SCRIPT_DIR}
COPY . ${SCRIPT_DIR}
RUN apt-get update && apt-get install -y rsync \
    && npm install -g pnpm \
    && chmod +x build-local.sh \
    && ./build-local.sh



