apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-replicasets-binding
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: list-replicasets
  apiGroup: rbac.authorization.k8s.io
