apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pvc-access
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"] # Include "patch" verb
